# Generated by Django 4.2.6 on 2023-10-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=221)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
