# Generated by Django 3.2.9 on 2023-02-20 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='following',
        ),
        migrations.AddField(
            model_name='myuser',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='_users_myuser_followings_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
