# Generated by Django 3.2.9 on 2023-02-20 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230220_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
