# Generated by Django 3.2.9 on 2023-03-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_alter_artlike_art'),
        ('users', '0006_alter_notification_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='following_artists',
            field=models.ManyToManyField(blank=True, related_name='followers', to='art.Artist'),
        ),
    ]
