# Generated by Django 4.2.1 on 2023-07-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        ('users', '0008_alter_myuser_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='following_artists',
            field=models.ManyToManyField(blank=True, related_name='followers', to='artist.artist'),
        ),
    ]
