# Generated by Django 4.2.1 on 2023-07-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_myuser_verify_alter_myuser_following_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reporter',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
