# Generated by Django 4.2.6 on 2023-10-14 09:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_alter_tweet_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet_like', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetlike',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='tweetlike',
            unique_together={('owner', 'tweet')},
        ),
    ]
